web/blueprints/main.py
"""
Blueprint for some general routes.

"""

from flask import Blueprint, g, render_template
from flask_login import current_user, login_required
from models.tabs import Favorite, Tab
from sqlalchemy import desc
from web.forms.tabs import SearchForm
from web.helpers import search_tabs

main = Blueprint("main", __name__)


@main.route("/")
def index():

    most_viewed = Tab.query.order_by(desc(Tab.views)).limit(5).all()
    recently_uploaded = Tab.query.order_by(desc(Tab.date_added)).limit(5).all()

    favs = []
    if current_user.is_authenticated:
        favorites = Favorite.query.filter_by(user_id=current_user.id).all()
        favs = [f.tab_id for f in favorites]

    return render_template(
        "main/index.html",
        title="Guitar Tabs",
        recently_uploaded=recently_uploaded,
        most_viewed=most_viewed,
        favs=favs,
    )


@main.route("/search")
def search():

    query = g.search_form.q.data

    results = []
    favs = []
    if query:
        results = search_tabs(query)

        if current_user.is_authenticated:
            favorites = Favorite.query.filter_by(user_id=current_user.id).all()
            favs = [f.tab_id for f in favorites]

    return render_template(
        "main/search.html",
        title="Guitar Tabs - Search",
        query=query,
        results=results,
        favs=favs,
    )


@main.route("/impressum")
def impressum():

    return render_template("main/impressum.html", title="Impressum")


@login_required
@main.route("/favorites")
def favorites():

    favs = []
    if current_user.is_authenticated:
        favorites = Favorite.query.filter_by(user_id=current_user.id).all()
        favs = [f.tab_id for f in favorites]

    fav_tabs = []
    for fav in favs:
        tab = Tab.query.get(fav)
        if tab:
            fav_tabs.append(tab)

    return render_template(
        "main/favorites.html", title="Favorites", favs=favs, fav_tabs=fav_tabs
    )

web/blueprints/tabs.py
"""
Blueprint for guitar tab routes

"""

from datetime import datetime
from flask import (
    Blueprint,
    g,
    flash,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from flask_login import current_user, login_required
from hashlib import sha256
from models.tabs import Favorite, Tab, TabFile
from web import app, db
from web.forms.tabs import EditForm, ReplaceFileForm, UploadForm
from web.helpers import make_redirect
import json
import os

tabs = Blueprint("tabs", __name__)


@tabs.route("/render/<tab_id>")
@tabs.route("/render/<tab_id>/<file_id>")
def render(tab_id, file_id=None):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    if not tab.views:
        tab.views = 1
    else:
        tab.views += 1
    db.session.commit()

    logs = {
        "render": [],
    }
    if os.path.isfile(g.config.get("log_file")):
        try:
            with open(g.config.get("log_file"), "r") as f:
                logs = json.loads(f.read())
                if not "render" in logs:
                    logs["render"] = []
        except Exception:
            pass

    username = "anonymous"
    if current_user.is_authenticated:
        username = current_user.username

    logs["render"].append(
        {
            "time": datetime.utcnow().isoformat(),
            "title": f"{tab.band} - {tab.song}",
            "user": username,
            "tabid": tab.id,
        }
    )
    with open(g.config.get("log_file"), "w") as f:
        f.write(json.dumps(logs))

    if file_id:
        tab.fileid = file_id

    is_favorite = False
    if current_user.is_authenticated:

        fav = Favorite.query.filter_by(user_id=current_user.id, tab_id=tab.id).all()
        if fav:
            is_favorite = True

    return render_template(
        "tabs/render.html", title=f"{tab.song} - Tabs", tab=tab, is_favorite=is_favorite
    )


@tabs.route("/browse")
def browse():

    tabs = Tab.query.order_by(Tab.song).order_by(Tab.band).all()

    favs = []
    if current_user.is_authenticated:
        favorites = Favorite.query.filter_by(user_id=current_user.id).all()
        favs = [f.tab_id for f in favorites]

    return render_template(
        "tabs/browse.html", title="Browse all tabs", tabs=tabs, favs=favs
    )


@tabs.route("/artist/<artist_name>")
def artist(artist_name):

    tabs_ = Tab.query.filter_by(band=artist_name).order_by(Tab.track).all()

    tabs = {}
    for t in tabs_:

        if t.album not in tabs:
            tabs[t.album] = [t]
        else:
            tabs[t.album].append(t)

    favs = []
    if current_user.is_authenticated:
        favorites = Favorite.query.filter_by(user_id=current_user.id).all()
        favs = [f.tab_id for f in favorites]

    return render_template(
        "tabs/artist.html",
        title=f"Tabs by {artist_name}",
        artist_name=artist_name,
        tabs=tabs,
        favs=favs,
    )


@tabs.route("/get-tab/<tab_id>")
@tabs.route("/get-tab/<tab_id>/<file_id>")
def get_tab(tab_id, file_id=None):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        return "Not Found (tab)", 404

    if not file_id:
        file_id = tab.fileid

    tabfile = TabFile.query.get(file_id)
    if not tabfile:
        return "Not Found (tabfile)", 404

    filename = os.path.join(app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext)
    if not os.path.isfile(filename):
        return "Not Found (file)", 404

    return send_file(filename)


@login_required
@tabs.route("/upload", methods=["GET", "POST"])
def upload():

    if not current_user.is_authenticated:

        flash("You are not logged in.", "danger")
        return redirect(url_for("auth.login"))

    form = UploadForm()

    if form.validate_on_submit():

        f = request.files.get("upload_file")
        if not f:
            flash("No file was selected.", "warning")
            return redirect(url_for("tabs.upload"))

        data = f.stream.read()
        digest = sha256(data).hexdigest()

        ext = os.path.splitext(f.filename)[1]

        tab = Tab(
            form.band.data,
            form.album.data,
            form.song.data,
            form.track.data,
        )
        db.session.add(tab)
        db.session.commit()

        tabfile = TabFile(digest, ext, tab.id)
        db.session.add(tabfile)
        db.session.commit()

        tab.fileid = tabfile.id
        db.session.commit()

        filename = os.path.join(
            app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext
        )
        with open(filename, "wb") as f:
            f.write(data)

        flash("File was uploaded", "success")
        return redirect(url_for("tabs.render", tab_id=tab.id))

    return render_template("tabs/upload.html", title="Upload a new tab", form=form)


@login_required
@tabs.route("/edit-metadata/<tab_id>", methods=["GET", "POST"])
def edit_metadata(tab_id):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    form = EditForm()

    if form.validate_on_submit():

        tab.band = form.band.data
        tab.album = form.album.data
        tab.song = form.song.data
        tab.track = form.track.data
        db.session.commit()

        flash(f"Metadata for {tab.song} was saved.", "success")

        return redirect(url_for("tabs.render", tab_id=tab.id))

    else:

        form.band.data = tab.band
        form.album.data = tab.album
        form.song.data = tab.song
        form.track.data = tab.track

    return render_template(
        "tabs/edit-metadata.html",
        title=f"Edit metadata for {tab.song}",
        form=form,
        tab=tab,
    )


@login_required
@tabs.route("/delete/<tab_id>")
def delete(tab_id):

    # NOTE: tab files to not currently get deleted!

    if not current_user.is_authenticated or not current_user.is_admin:
        flash("Only an admin can delete tabs.", "danger")
        return redirect(url_for("tabs.render", tab_id=tab_id))

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    db.session.delete(tab)
    db.session.commit()

    flash("Tab was deleted.", "success")
    return redirect(url_for("main.index"))


@tabs.route("/download_gp/<tab_id>")
@tabs.route("/download_gp/<tab_id>/<file_id>")
def download_gp(tab_id, file_id=None):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    if not file_id:
        file_id = tab.fileid

    tabfile = TabFile.query.get(file_id)
    if not tabfile:
        flash("Tab file not found.", "danger")
        return redirect(url_for("main.index"))

    filename = os.path.join(app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext)
    if not os.path.isfile(filename):
        return "Not Found", 404

    attachment_filename = f"{tab.band} - {tab.song}{tabfile.ext}"

    return send_file(
        filename, as_attachment=True, attachment_filename=attachment_filename
    )


@login_required
@tabs.route("/versions/<tab_id>")
def versions(tab_id):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    tabfiles = TabFile.query.filter_by(tabid=tab.id)

    form = ReplaceFileForm()

    return render_template(
        "tabs/versions.html",
        title=f"Upload new tab for {tab.song}",
        form=form,
        tab=tab,
        tabfiles=tabfiles,
    )


@login_required
@tabs.route("/upload-file/<tab_id>", methods=["POST"])
def upload_file(tab_id):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index", tab_id=tab.id))

    form = ReplaceFileForm()

    f = request.files.get("upload_file")
    if not f:
        flash("No file was selected.", "warning")
        return redirect(url_for("tabs.versions", tab_id=tab.id))

    data = f.stream.read()
    digest = sha256(data).hexdigest()

    ext = os.path.splitext(f.filename)[1]

    tabfile = TabFile(digest, ext, tab.id, form.comment.data)
    db.session.add(tabfile)
    db.session.commit()

    tab.fileid = tabfile.id
    db.session.commit()

    filename = os.path.join(app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext)
    with open(filename, "wb") as f:
        f.write(data)

    flash("File was uploaded.", "success")
    return redirect(url_for("tabs.render", tab_id=tab.id))


@login_required
@tabs.route("/delete-file/<tab_id>/<file_id>")
def delete_file(tab_id, file_id):

    if current_user.is_authenticated and not current_user.is_admin:
        flash("Only admins can delete files", "warning")
        return redirect(url_for("tabs.versions", tab_id=tab_id))

    tab = Tab.query.filter_by(fileid=file_id).all()
    if tab:
        flash("Cannot delete active tab file", "warning")
        return redirect(url_for("tabs.versions", tab_id=tab_id))

    tabfile = TabFile.query.get(file_id)
    if not tabfile:
        flash("Tab file not found", "warning")
        return redirect(url_for("tabs.versions", tab_id=tab_id))

    filename = os.path.join(app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext)
    os.remove(filename)

    db.session.delete(tabfile)
    db.session.commit()

    flash("Tab file was deleted", "success")
    return redirect(url_for("tabs.versions", tab_id=tab_id))


@login_required
@tabs.route("/activate-file/<tab_id>/<file_id>")
def activate_file(tab_id, file_id):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("tabs.versions", tab_id=tab_id))

    tabfile = TabFile.query.get(file_id)
    if not tabfile:

web/templates/main/favorites.html
{% extends 'base.html' %}

{% block content %}

  <h3>Favorites</h3>

  {% if not favs %}

    <div class="alert alert-info">
      You have not favorited any tabs yet..
    </div>

  {% else %}

    <ul class="list-group">
      {% for fav in fav_tabs %}
        <li class="list-group-item">
          <a href="{{ url_for('tabs.render', tab_id=fav.id) }}">
            {{ fav.band }} · {{ fav.song }}
          </a>
        </li>
      {% endfor %}
    </ul>

  {% endif %}

{% endblock %}

web/templates/main/impressum.html
{% extends 'base.html' %}

{% block content %}

  <h3>Impressum</h3>

  <h5 class="mt-3 mb-3">Attributions</h5>

  <p>Icons are used from FontAwesome5.</p>

  <p>
    The Favicon was also created by FontAwesome
    (<a href="https://fontawesome.com/icons/guitar?style=solid" target="blank">see here</a>).
  </p>

  <p>
    The sheet music is rendered with
    <a href="https://www.alphatab.net/" target="blank">alphaTab</a>.
  </p>

{% endblock %}

web/templates/main/index.html
{% extends 'base.html' %}

{% block content %}

  <div class="row">
    <div class="col-md-6">
      <h5 class="mt-3">Most viewed</h5>

      <ul class="list-group">
        {% if most_viewed %}
          {% for t in most_viewed %}
            <li class="list-group-item">
              <a href="{{ url_for('tabs.render', tab_id=t.id) }}">
                {{ t.band }} · {{ t.song }}
                {% if t.id in favs %}<i class="fa fa-star"></i>{% endif %}
              </a>
            </li>
          {% endfor %}
        {% else %}
          <div class="alert alert-warning">
            No tabs available yet.
          </div>
        {% endif %}
      </ul>
    </div>

    <div class="col-md-6">
      <h5 class="mt-3">Recently added</h5>

      <ul class="list-group">
        {% if recently_uploaded %}
          {% for t in recently_uploaded %}
            <li class="list-group-item">
              <a href="{{ url_for('tabs.render', tab_id=t.id) }}">
                {{ t.band }} · {{ t.song }}
                {% if t.id in favs %}<i class="fa fa-star"></i>{% endif %}
              </a>
            </li>
          {% endfor %}
        {% else %}
          <div class="alert alert-warning">
            No tabs available yet.
          </div>
        {% endif %}
      </ul>
    </div>
  </div>

  <a href="{{ url_for('tabs.browse') }}" class="btn btn-outline-dark mt-3">
    <i class="fa-solid fa-rectangle-list"></i>
    Browse all
  </a>

{% endblock %}

web/templates/main/search.html
{% extends 'base.html' %}

{% block content %}

  <h3 class="me-auto">
    {% if query %}
      Searching for "{{ query }}"
    {% else %}
      Search
    {% endif %}
  </h3>

  {% if query and not results %}
    <div class="mt-3 alert alert-warning">
      No results found.
    </div>
  {% elif results %}
    <ul class="list-group mt-3">
      {% for t in results %}
        <li class="list-group-item">
          <a href="{{ url_for('tabs.render', tab_id=t.id) }}">
            {{ t.band }} · {{ t.song }}
            {% if t.id in favs %}<i class="fa fa-star"></i>{% endif %}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}

{% endblock %}