web/blueprints/auth.py
"""
Blueprint for the authentication process.

The first user has to be created from the cli.
All new users can be created by an admin.
"""

from flask import Blueprint, flash, g, render_template
from flask_login import current_user, login_user, logout_user
from models.user import User
from web import db
from web.forms.auth import LoginForm, RegistrationForm
from web.helpers import make_redirect

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    """User login route."""

    # redirect to index, if the user is already logged in
    if current_user.is_authenticated:
        return make_redirect("main.index")

    form = LoginForm()
    if form.validate_on_submit():

        # validation is done by the login form
        user = User.query.filter_by(username=form.username.data).first()

        login_user(user, remember=form.remember_me.data)
        flash("Logged in.", "success")

        return make_redirect("main.index")

    return render_template("auth/login.html", title="Sign in", form=form)


@auth.route("/logout")
def logout():
    """Log the current user out."""

    logout_user()
    flash("Logged out.", "success")

    return make_redirect("main.index")


@auth.route("/register", methods=["GET", "POST"])
def register():

    if current_user.is_authenticated:
        return make_redirect("main.index")

    form = RegistrationForm()

    if form.validate_on_submit():

        # validation is done by the registration form
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)

        users = User.query.all()
        if not users:
            user.is_admin = True

        db.session.add(user)
        db.session.commit()

        flash("Registration successful.", "success")

        return make_redirect("auth.login")

    return render_template(
        "auth/register.html",
        title="Register",
        form=form,
        registration_enabled=g.config.get("registration_enabled"),
    )

web/blueprints/main.py
"""
Blueprint for some general routes.

"""

from flask import Blueprint, g, render_template
from flask_login import current_user, login_required
from models.tabs import Favorite, Tab
from sqlalchemy import desc
from web.forms.tabs import SearchForm
from web.helpers import search_tabs

main = Blueprint("main", __name__)


@main.route("/")
def index():

    most_viewed = Tab.query.order_by(desc(Tab.views)).limit(5).all()
    recently_uploaded = Tab.query.order_by(desc(Tab.date_added)).limit(5).all()

    favs = []
    if current_user.is_authenticated:
        favorites = Favorite.query.filter_by(user_id=current_user.id).all()
        favs = [f.tab_id for f in favorites]

    return render_template(
        "main/index.html",
        title="Guitar Tabs",
        recently_uploaded=recently_uploaded,
        most_viewed=most_viewed,
        favs=favs,
    )


@main.route("/search")
def search():

    query = g.search_form.q.data

    results = []
    favs = []
    if query:
        results = search_tabs(query)

        if current_user.is_authenticated:
            favorites = Favorite.query.filter_by(user_id=current_user.id).all()
            favs = [f.tab_id for f in favorites]

    return render_template(
        "main/search.html",
        title="Guitar Tabs - Search",
        query=query,
        results=results,
        favs=favs,
    )


@main.route("/impressum")
def impressum():

    return render_template("main/impressum.html", title="Impressum")


@login_required
@main.route("/favorites")
def favorites():

    favs = []
    if current_user.is_authenticated:
        favorites = Favorite.query.filter_by(user_id=current_user.id).all()
        favs = [f.tab_id for f in favorites]

    fav_tabs = []
    for fav in favs:
        tab = Tab.query.get(fav)
        if tab:
            fav_tabs.append(tab)

    return render_template(
        "main/favorites.html", title="Favorites", favs=favs, fav_tabs=fav_tabs
    )

web/templates/base.html
<!--
  vi: ft=htmldjango
-->

<!doctype html>

<html lang="en">

  <meta charset="utf-8">
  <meta name="description" content="Guitar Tabs">
  <meta name="viewport" content="width=device-width">
  <meta http-equiv="content-type" content="text/html; charset=utf-8">

  <link rel="icon" type="image/ico" href="{{ url_for('static', filename='img/favicon.ico') }}">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='fonts/fa/css/all.min.css') }}">

  {% block style %}
    {# style additions #}
  {% endblock %}

  {% block title %}
    {% if title %}
      <title>{{ title }}</title>
    {% else %}
      <title>{{ g.config.app_name }}</title>
    {% endif %}
  {% endblock %}

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">
        <i class="fa fa-guitar"></i>
        Guitar Tabs
      </a>

      {% if current_user.is_authenticated %}
        <div class="ms-0 text-muted me-auto" style="font-size: 60%">{{ g.request_time() }}</div>
      {% endif %}

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a href="{{ url_for('tabs.upload') }}" class="nav-link">
              <i class="fa fa-file-upload"></i>
              Upload new tab
            </a>
          </li>
        </ul>
        {% if current_user.is_authenticated %}
          <div class="d-flex mt-2 mt-lg-0">
            <a class="btn btn-outline-primary me-2" href="{{ url_for('main.favorites') }}">
              <i class="fa fa-star" title="Favorites"></i>
            </a>
            {# <a class="btn btn-outline-primary me-2" href="#">
              <i class="fa fa-cogs" title="User settings"></i>
            </a> #}
            {% if current_user.is_admin %}
              <a class="btn btn-outline-primary me-2" href="{{ url_for('admin.settings') }}">
                <i class="fa fa-toolbox" title="Admin settings"></i>
              </a>
            {% endif %}
          </div>
        {% endif %}
        <div class="d-flex mt-2 mt-lg-0">
          {% if current_user.is_authenticated %}
            <a class="btn btn-outline-dark" href="{{ url_for('auth.logout') }}">
              Log out
            </a>
          {% else %}
            <a class="btn btn-outline-primary me-2" href="{{ url_for('auth.login') }}">
              Log in
            </a>
            <a class="btn btn-primary" href="{{ url_for('auth.register') }}">
              Sign up
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

  <div class="bg-light">
    <div class="container pb-4 pt-4">

      <form class="form" action="{{ url_for('main.search') }}" method="get" novalidate>
        <div class="input-group" style="width: auto;">
          {{ g.search_form.q(class='form-control', placeholder='Search', style="max-width: 25rem;") }}
          <button type="submit" class="btn btn-outline-secondary" style="min-width: 6rem;">
            <i class="fa fa-search"></i>
            Search
          </button>
        </div>
      </form>

    </div>
  </div>

  <div class="container mt-3">

    {% block content %}
    {% endblock %}

  </div>

  <div class="mt-3 ms-3 me-3">

    {% block fullwidth %}
    {% endblock %}

  </div>

  {% block footer %}
    <div class="container mt-3 mb-4">
      <hr>

      <div class="row">
        <div class="col-6">
          <span class="text-muted ml-2">
            Copyright (c) 2022 Philipp Glaum
          </span>
        </div>
        <div class="col-6 text-end">
          <a href="{{ url_for('main.impressum') }}">
            Impressum
          </a>
        </div>
      </div>
    </div>
  {% endblock %}

  {% block flash %}
    <div id="flashed-messages">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            {% if category == 'message' %}
              {% set category = 'info' %}
            {% endif %}

            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
              {{ message|safe }}
              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>

    <style>
      #flashed-messages {
        position: fixed;
        bottom: 1em;
        right: 1em;
        margin-left: 1em;
      }
    </style>
  {% endblock %}

  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>

  <script>
    function js_error() {
      $('#flashed-messages').append(`
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          An error has ocurred. Please reload the page to avoid unforseeable
          states.
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      `);
    }

    function flash_message(message, type) {
      $('#flashed-messages').append('<div class="alert alert-' + type +
        ' alert-dismissible fade show" role="alert">' + message +
        '<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>');
    }
  </script>

  <script>
    console.log('Page rendering took {{ g.request_time() }}');
  </script>

  {% block script %}
    {# script additions #}
  {% endblock %}

</html>

web/templates/forms.jinja
{#
  vi: ft=htmldjango
#}

{% macro input_is_valid(form_input) %}
  <div class="mb-3">
    {{ form_input.label(class="form-label") }}
    {{ form_input(class="form-control is-valid") }}
    {% for error in form_input.errors %}
      <div class="form-text text-danger">{{ error|safe }}</div>
    {% endfor %}
  </div>
{% endmacro %}

{% macro input_with_invalid(form_input) %}
  <div class="mb-3">
    {{ form_input.label(class="form-label") }}
    {{ form_input(class="form-control" + (" is-invalid" if form_input.errors else "")) }}
    {% for error in form_input.errors %}
      <div class="form-text text-danger">{{ error|safe }}</div>
    {% endfor %}
  </div>
{% endmacro %}

{% macro input_with_invalid_and_valid(form_input) %}
  <div class="mb-3">
    {{ form_input.label(class="form-label") }}
    {{ form_input(class="form-control" + (" is-invalid" if form_input.errors else "") + (" is-valid" if not form_input.errors and validated else "")) }}
    {% for error in form_input.errors %}
      <div class="form-text text-danger">{{ error|safe }}</div>
    {% endfor %}
  </div>
{% endmacro %}

{% macro input(form_input) %}
  <div class="mb-3">
    {{ form_input.label(class="form-label") }}
    {{ form_input(class="form-control") }}
  </div>
{% endmacro %}

{% macro textarea(form_input, rows=16) %}
  <div class="mb-3">
    {{ form_input.label(class="form-label") }}
    {{ form_input(class="form-control", rows=rows) }}
  </div>
{% endmacro %}

{% macro input_check(form_input) %}
  <div class="form-check mb-3">
    {{ form_input(class="form-check-input") }}
    {{ form_input.label(class="form-check-label") }}
  </div>
{% endmacro %}

{% macro input_check_with_description(form_input, description) %}
  <div class="form-group mb-3">
    <div class="form-check">
      {{ form_input(class="form-check-input") }}
      {{ form_input.label(class="form-check-label") }}

      <a class="text-dark" data-toggle="tooltip" data-placement="right" title="{{ description }}">
        <i class="fa fa-info-circle"></i>
      </a>
    </div>
  </div>
{% endmacro %}

{% macro submit_submit() %}
  <button type="submit" class="btn btn-outline-primary">
    Submit
  </button>
{% endmacro %}

{% macro submit_save() %}
  <button type="submit" class="btn btn-outline-primary">
    <i class="fa fa-save"></i>
    Save
  </button>
{% endmacro %}

{% macro submit_add() %}
  <button type="submit" class="btn btn-primary">
    <i class="fa fa-plus"></i>
    Add
  </button>
{% endmacro %}

{% macro submit_create() %}
  <button type="submit" class="btn btn-primary">
    <i class="fa fa-plus-square"></i>
    Create
  </button>
{% endmacro %}

{% macro submit_search() %}
  <button type="submit" class="btn btn-primary">
    <i class="fa fa-search"></i>
    Search
  </button>
{% endmacro %}

{% macro input_hidden(form_input) %}
  {{ form_input(hidden=True) }}
{% endmacro %}

web/templates/quick.jinja
{#
  vi: ft=htmldjango
#}

{% macro really_delete(button_text, modal_title, modal_body, url) %}
  <button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#really-delete-modal">
    <i class="fa fa-trash"></i>
    {{ button_text }}
  </button>

  <div class="modal" tabindex="-1" id="really-delete-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">{{ modal_title }}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <p>{{ modal_body }}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <a class="btn btn-danger" href="{{ url }}">
            <i class="fa fa-trash"></i>
            Delete
          </a>
        </div>
      </div>
    </div>
  </div>
{% endmacro %}