web/forms/tabs.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import FileField, IntegerField, StringField
from wtforms.validators import DataRequired


class UploadForm(FlaskForm):

    upload_file = FileField("Guitar Pro File", validators=[DataRequired()])

    band = StringField("Band", validators=[DataRequired()])
    album = StringField("Album", validators=[DataRequired()])
    song = StringField("Song", validators=[DataRequired()])
    track = IntegerField("Track", default=0)


class ReplaceFileForm(FlaskForm):

    upload_file = FileField("Guitar Pro File", validators=[DataRequired()])
    comment = StringField("Update Comment", default="updated version")


class EditForm(FlaskForm):

    band = StringField("Band", validators=[DataRequired()])
    album = StringField("Album", validators=[DataRequired()])
    song = StringField("Song", validators=[DataRequired()])
    track = IntegerField("Track", default=0)


class SearchForm(FlaskForm):

    q = StringField("Search", validators=[DataRequired()])

    def __init__(self, *args, **kwargs):

        if "formdata" not in kwargs:
            kwargs["formdata"] = request.args
        if "csrf_enabled" not in kwargs:
            kwargs["csrf_enabled"] = False

        super(SearchForm, self).__init__(*args, **kwargs)

web/blueprints/tabs.py
"""
Blueprint for guitar tab routes

"""

from datetime import datetime
from flask import (
    Blueprint,
    g,
    flash,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from flask_login import current_user, login_required
from hashlib import sha256
from models.tabs import Favorite, Tab, TabFile
from web import app, db
from web.forms.tabs import EditForm, ReplaceFileForm, UploadForm
from web.helpers import make_redirect
import json
import os

tabs = Blueprint("tabs", __name__)


@tabs.route("/render/<tab_id>")
@tabs.route("/render/<tab_id>/<file_id>")
def render(tab_id, file_id=None):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    if not tab.views:
        tab.views = 1
    else:
        tab.views += 1
    db.session.commit()

    logs = {
        "render": [],
    }
    if os.path.isfile(g.config.get("log_file")):
        try:
            with open(g.config.get("log_file"), "r") as f:
                logs = json.loads(f.read())
                if not "render" in logs:
                    logs["render"] = []
        except Exception:
            pass

    username = "anonymous"
    if current_user.is_authenticated:
        username = current_user.username

    logs["render"].append(
        {
            "time": datetime.utcnow().isoformat(),
            "title": f"{tab.band} - {tab.song}",
            "user": username,
            "tabid": tab.id,
        }
    )
    with open(g.config.get("log_file"), "w") as f:
        f.write(json.dumps(logs))

    if file_id:
        tab.fileid = file_id

    is_favorite = False
    if current_user.is_authenticated:

        fav = Favorite.query.filter_by(user_id=current_user.id, tab_id=tab.id).all()
        if fav:
            is_favorite = True

    return render_template(
        "tabs/render.html", title=f"{tab.song} - Tabs", tab=tab, is_favorite=is_favorite
    )


@tabs.route("/browse")
def browse():

    tabs = Tab.query.order_by(Tab.song).order_by(Tab.band).all()

    favs = []
    if current_user.is_authenticated:
        favorites = Favorite.query.filter_by(user_id=current_user.id).all()
        favs = [f.tab_id for f in favorites]

    return render_template(
        "tabs/browse.html", title="Browse all tabs", tabs=tabs, favs=favs
    )


@tabs.route("/artist/<artist_name>")
def artist(artist_name):

    tabs_ = Tab.query.filter_by(band=artist_name).order_by(Tab.track).all()

    tabs = {}
    for t in tabs_:

        if t.album not in tabs:
            tabs[t.album] = [t]
        else:
            tabs[t.album].append(t)

    favs = []
    if current_user.is_authenticated:
        favorites = Favorite.query.filter_by(user_id=current_user.id).all()
        favs = [f.tab_id for f in favorites]

    return render_template(
        "tabs/artist.html",
        title=f"Tabs by {artist_name}",
        artist_name=artist_name,
        tabs=tabs,
        favs=favs,
    )


@tabs.route("/get-tab/<tab_id>")
@tabs.route("/get-tab/<tab_id>/<file_id>")
def get_tab(tab_id, file_id=None):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        return "Not Found (tab)", 404

    if not file_id:
        file_id = tab.fileid

    tabfile = TabFile.query.get(file_id)
    if not tabfile:
        return "Not Found (tabfile)", 404

    filename = os.path.join(app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext)
    if not os.path.isfile(filename):
        return "Not Found (file)", 404

    return send_file(filename)


@login_required
@tabs.route("/upload", methods=["GET", "POST"])
def upload():

    if not current_user.is_authenticated:

        flash("You are not logged in.", "danger")
        return redirect(url_for("auth.login"))

    form = UploadForm()

    if form.validate_on_submit():

        f = request.files.get("upload_file")
        if not f:
            flash("No file was selected.", "warning")
            return redirect(url_for("tabs.upload"))

        data = f.stream.read()
        digest = sha256(data).hexdigest()

        ext = os.path.splitext(f.filename)[1]

        tab = Tab(
            form.band.data,
            form.album.data,
            form.song.data,
            form.track.data,
        )
        db.session.add(tab)
        db.session.commit()

        tabfile = TabFile(digest, ext, tab.id)
        db.session.add(tabfile)
        db.session.commit()

        tab.fileid = tabfile.id
        db.session.commit()

        filename = os.path.join(
            app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext
        )
        with open(filename, "wb") as f:
            f.write(data)

        flash("File was uploaded", "success")
        return redirect(url_for("tabs.render", tab_id=tab.id))

    return render_template("tabs/upload.html", title="Upload a new tab", form=form)


@login_required
@tabs.route("/edit-metadata/<tab_id>", methods=["GET", "POST"])
def edit_metadata(tab_id):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    form = EditForm()

    if form.validate_on_submit():

        tab.band = form.band.data
        tab.album = form.album.data
        tab.song = form.song.data
        tab.track = form.track.data
        db.session.commit()

        flash(f"Metadata for {tab.song} was saved.", "success")

        return redirect(url_for("tabs.render", tab_id=tab.id))

    else:

        form.band.data = tab.band
        form.album.data = tab.album
        form.song.data = tab.song
        form.track.data = tab.track

    return render_template(
        "tabs/edit-metadata.html",
        title=f"Edit metadata for {tab.song}",
        form=form,
        tab=tab,
    )


@login_required
@tabs.route("/delete/<tab_id>")
def delete(tab_id):

    # NOTE: tab files to not currently get deleted!

    if not current_user.is_authenticated or not current_user.is_admin:
        flash("Only an admin can delete tabs.", "danger")
        return redirect(url_for("tabs.render", tab_id=tab_id))

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    db.session.delete(tab)
    db.session.commit()

    flash("Tab was deleted.", "success")
    return redirect(url_for("main.index"))


@tabs.route("/download_gp/<tab_id>")
@tabs.route("/download_gp/<tab_id>/<file_id>")
def download_gp(tab_id, file_id=None):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    if not file_id:
        file_id = tab.fileid

    tabfile = TabFile.query.get(file_id)
    if not tabfile:
        flash("Tab file not found.", "danger")
        return redirect(url_for("main.index"))

    filename = os.path.join(app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext)
    if not os.path.isfile(filename):
        return "Not Found", 404

    attachment_filename = f"{tab.band} - {tab.song}{tabfile.ext}"

    return send_file(
        filename, as_attachment=True, attachment_filename=attachment_filename
    )


@login_required
@tabs.route("/versions/<tab_id>")
def versions(tab_id):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index"))

    tabfiles = TabFile.query.filter_by(tabid=tab.id)

    form = ReplaceFileForm()

    return render_template(
        "tabs/versions.html",
        title=f"Upload new tab for {tab.song}",
        form=form,
        tab=tab,
        tabfiles=tabfiles,
    )


@login_required
@tabs.route("/upload-file/<tab_id>", methods=["POST"])
def upload_file(tab_id):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("main.index", tab_id=tab.id))

    form = ReplaceFileForm()

    f = request.files.get("upload_file")
    if not f:
        flash("No file was selected.", "warning")
        return redirect(url_for("tabs.versions", tab_id=tab.id))

    data = f.stream.read()
    digest = sha256(data).hexdigest()

    ext = os.path.splitext(f.filename)[1]

    tabfile = TabFile(digest, ext, tab.id, form.comment.data)
    db.session.add(tabfile)
    db.session.commit()

    tab.fileid = tabfile.id
    db.session.commit()

    filename = os.path.join(app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext)
    with open(filename, "wb") as f:
        f.write(data)

    flash("File was uploaded.", "success")
    return redirect(url_for("tabs.render", tab_id=tab.id))


@login_required
@tabs.route("/delete-file/<tab_id>/<file_id>")
def delete_file(tab_id, file_id):

    if current_user.is_authenticated and not current_user.is_admin:
        flash("Only admins can delete files", "warning")
        return redirect(url_for("tabs.versions", tab_id=tab_id))

    tab = Tab.query.filter_by(fileid=file_id).all()
    if tab:
        flash("Cannot delete active tab file", "warning")
        return redirect(url_for("tabs.versions", tab_id=tab_id))

    tabfile = TabFile.query.get(file_id)
    if not tabfile:
        flash("Tab file not found", "warning")
        return redirect(url_for("tabs.versions", tab_id=tab_id))

    filename = os.path.join(app.config.get("DATA_DIR"), tabfile.sha256 + tabfile.ext)
    os.remove(filename)

    db.session.delete(tabfile)
    db.session.commit()

    flash("Tab file was deleted", "success")
    return redirect(url_for("tabs.versions", tab_id=tab_id))


@login_required
@tabs.route("/activate-file/<tab_id>/<file_id>")
def activate_file(tab_id, file_id):

    tab = Tab.query.filter_by(id=tab_id).first()
    if not tab:
        flash("Tab not found.", "danger")
        return redirect(url_for("tabs.versions", tab_id=tab_id))

    tabfile = TabFile.query.get(file_id)
    if not tabfile:

web/templates/tabs/artist.html
{% extends 'base.html' %}

{% block content %}

  <h3>Tabs by: {{ artist_name }}</h3>

  <div class="row">
    {% for x in tabs.keys() %}
      <div class="col-md-6">
        <h5>{{ x }}</h5>

        <ul>
          {% for y in tabs[x] %}
            <li>
              <a href="{{ url_for('tabs.render', tab_id=y.id) }}">
                {{ y.song }}
                {% if y.id in favs %}<i class="fa fa-star"></i>{% endif %}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    {% endfor %}
  </div>

{% endblock %}

web/templates/tabs/browse.html
{% extends 'base.html' %}

{% block content %}

  <h3>Browse all tabs</h3>

  <div>
    <ul class="list-group">
      {% for t in tabs %}
        <li class="list-group-item">
          <a href="{{ url_for('tabs.render', tab_id=t.id) }}">
            {{ t.band }} · {{ t.song }}
            {% if t.id in favs %}<i class="fa fa-star"></i>{% endif %}
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>

{% endblock %}

web/templates/tabs/edit-metadata.html
{% extends 'base.html' %}

{% import 'forms.jinja' as f %}

{% block content %}

  <h3>Edit metadata for "{{ tab.song }}"</h3>

  <div class="row">
    <div class="col-md-6">

      <form action="" method="post" enctype="multipart/form-data" novalidate>

        {{ form.hidden_tag() }}

        {{ f.input(form.song) }}
        {{ f.input(form.album) }}
        {{ f.input(form.band) }}
        {{ f.input(form.track) }}

        <div>
          <a class="btn btn-outline-secondary" href="{{ url_for('tabs.render', tab_id=tab.id) }}">
            <i class="fa fa-caret-left"></i>
            Cancel
          </a>
          <button type="submit" class="btn btn-primary me-2">
            <i class="fa fa-save"></i>
            Save
          </button>
        </div>

      </form>

    </div>
  </div>

{% endblock %}

web/templates/tabs/render.html
{% extends 'base.html' %}

{% import 'forms.jinja' as f %}

{% block content %}

  <!-- <script src="https://cdn.jsdelivr.net/npm/@coderline/alphatab@latest/dist/alphaTab.js"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/@coderline/alphatab@1.3.0-alpha.131/dist/alphaTab.min.js"></script>

  <style type="text/css">
    {% include 'css/render.css' %}
  </style>

  <h3>
    <a href="{{ url_for('tabs.artist', artist_name=tab.band) }}">{{ tab.band }}</a>
    ·
    {{ tab.song }}
    {% if is_favorite %}<i class="fa fa-star"></i>{% endif %}
  </h3>

  <div class="mb-3">

    {% if current_user.is_authenticated %}
      {% if is_favorite %}
        <a class="btn btn-secondary me-2 mt-2"
           href="{{ url_for('tabs.unfav_tab', tab_id=tab.id, next=url_for('tabs.render', tab_id=tab.id)) }}">
          <i class="far fa-star"></i>
          Unfavorite
        </a>
      {% else %}
        <a class="btn btn-outline-secondary me-2 mt-2"
           href="{{ url_for('tabs.fav_tab', tab_id=tab.id, next=url_for('tabs.render', tab_id=tab.id)) }}">
          <i class="fa fa-star"></i>
          Favorite
        </a>
      {% endif %}

      <a href="{{ url_for('tabs.versions', tab_id=tab.id) }}"
        class="btn btn-outline-secondary me-2 mt-2">
        <i class="fa fa-code-branch"></i>
        Versions
      </a>

      <a href="{{ url_for('tabs.edit_metadata', tab_id=tab.id) }}"
        class="btn btn-outline-secondary me-2 mt-2">
        <i class="fa fa-edit"></i>
        Edit metadata
      </a>
    {% endif %}

    <a href="{{ url_for('tabs.download_gp', tab_id=tab.id, file_id=tab.fileid) }}"
       class="btn btn-outline-success me-2 mt-2">
      <i class="fa fa-file-download"></i>
      Download
    </a>
    {% if current_user.is_authenticated and current_user.is_admin %}
      <a href="{{ url_for('tabs.delete', tab_id=tab.id) }}"
        class="btn btn-outline-danger me-2 mt-2">
        <i class="fa fa-trash"></i>
        Delete
      </a>
    {% endif %}

  </div>

{% endblock %}

{% block fullwidth %}

  <div class="at-wrap">
    <div class="at-overlay">
      <div class="at-overlay-content">
        <div class="d-flex align-items-center">
          <div class="spinner-border me-3" role="status"></div>
          <div>Music sheet is loading...</div>
        </div>
      </div>
    </div>

    <div class="sticky-top">
      <div class="at-controls bg-light row pt-1">
        <div class="at-controls-left me-2 ms-2 mb-2 d-flex flex-wrap align-items-center">

          <span class="mt-1 at-player-progress">0%</span>

          <a class="mt-1 btn btn-outline-dark at-player-stop disabled" title="stop">
            <i class="fas fa-step-backward"></i>
          </a>

          <a class="mt-1 btn btn-outline-dark at-player-play-pause disabled ms-1" title="play">
            <i class="fas fa-play"></i>
          </a>

          <div class="mt-1 at-song-position d-none d-lg-block ms-2">00:00 / 00:00</div>

          <div class="mt-1 dropdown at-tracks d-block ms-auto">
            <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown">
              <i class="fa fa-guitar"></i>
            </button>
            <ul id="track-list-dropdown" class="dropdown-menu at-track-list">
            </ul>
          </div>

          <button type="button" class="mt-1 ms-2 btn btn-outline-dark" data-bs-toggle="modal" data-bs-target="#player-settings">
            <i class="fa fa-cogs"></i>
          </button>

        </div>
      </div>
    </div>

    <div class="at-content">
      <div class="at-viewport">
        <div class="at-main"></div>
      </div>
    </div>
  </div>

  <template id="at-track-template">
    <li class="at-track">
      <button class="dropdown-item">
        <div class="at-track-details">
          <div class="at-track-name"></div>
        </div>
      </button>
    </li>
  </template>

  <div class="modal fade" id="player-settings" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Player settings</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal">
          </button>
        </div>

        <div class="modal-body">

          <div class="mt-0">
            <strong>View</strong>
          </div>

          <div class="d-flex flex-wrap">
            <div id="at-layout" class="mt-1 me-1 dropdown">
              <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown">
                <i class="fa fa-list"></i>
                Layout
              </button>
              <ul class="dropdown-menu">
                <li><button class="dropdown-item" data-value="horizontal">Horizontal</button></li>
                <li><button class="dropdown-item active" data-value="page">Page</button></li>
              </ul>
            </div>

            <div class="mt-1 me-1 dropdown" id="at-zoom">
              <button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown">
                <i class="fa fa-search"></i>
                Zoom
              </button>
              <ul class="dropdown-menu">
                <li><button class="dropdown-item" data-value="25">25%</button></li>
                <li><button class="dropdown-item" data-value="50">50%</button></li>
                <li><button class="dropdown-item" data-value="75">75%</button></li>
                <li><button class="dropdown-item" data-value="90">90%</button></li>
                <li><button class="dropdown-item active" data-value="100">100%</button></li>
                <li><button class="dropdown-item" data-value="110">110%</button></li>
                <li><button class="dropdown-item" data-value="125">125%</button></li>
                <li><button class="dropdown-item" data-value="150">150%</button></li>
                <li><button class="dropdown-item" data-value="200">200%</button></li>
              </select>
            </div>
          </div>

          <div class="mt-2">
            <strong>Playback</strong>
          </div>

          <div class="form-check mb-2">
            <input id="ps-metronome" class="form-check-input" type="checkbox">
            <label for="ps-metronome" class="form-check-label">Metronome</label>
          </div>

          <div class="form-check mb-2">
            <input id="ps-loop" class="form-check-input" type="checkbox">
            <label for="ps-loop" class="form-check-label">Loop</label>
          </div>

          <div>
            <div>
              Playback speed
            </div>
            <select id="ps-speed" class="form-select">
              <option value="50">50%</option>
              <option value="60">60%</option>
              <option value="70">70%</option>
              <option value="80">80%</option>
              <option value="90">90%</option>
              <option value="100" selected>100%</option>
              <option value="110">110%</option>
            </select>
          </div>

          <div>
            <label for="ps-custom-speed" class="form-label">Custom speed</label>
            <input id="ps-custom-speed" type="number" value="100" class="form-control">
          </div>

          <div>
            <div>
              Transpose
            </div>
            <select id="ps-transpose" class="form-select">
              <option value="-3">-3</option>
              <option value="-2">-2</option>
              <option value="-1">-1</option>
              <option value="0" selected>0</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
            </select>
          </div>

          <div class="mt-2">
            <strong>Tracks</strong>
          </div>

          <div id="ps-track-list"></div>

          <div class="mt-2">
            <strong>Other</strong>
          </div>

          <div>
            <a id="at-print" class="btn btn-outline-dark" title="print">
              <i class="fas fa-print"></i>
              Print
            </a>
          </div>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-bs-dismiss="modal">
            <i class="fa fa-check"></i>
            Done
          </button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block script %}

  <script type="text/javascript">
    {% include 'js/render.js' %}
  </script>

{% endblock %}

{% block footer %}{% endblock %}

web/templates/tabs/upload.html
{% extends 'base.html' %}

{% import 'forms.jinja' as f %}

{% block content %}

  <h3>Upload a new Guitar Tab</h3>

  <div class="row">
    <div class="col-md-6">

      <form action="" method="post" enctype="multipart/form-data" novalidate>

        {{ form.hidden_tag() }}

        {{ f.input_with_invalid(form.upload_file) }}
        {{ f.input_with_invalid(form.song) }}
        {{ f.input_with_invalid(form.album) }}
        {{ f.input_with_invalid(form.band) }}
        {{ f.input(form.track) }}

        <a href="{{ url_for('main.index') }}" class="btn btn-outline-secondary">
          <i class="fa fa-caret-left"></i>
          Cancel
        </a>
        <button type="submit" class="btn btn-primary">
          <i class="fa fa-file-upload"></i>
          Upload
        </button>

      </form>

    </div>
  </div>

{% endblock %}

web/templates/tabs/versions.html
{% extends 'base.html' %}

{% import 'forms.jinja' as f %}

{% block content %}

  <h3>Versions for "{{ tab.song }}"</h3>

  <a href="{{ url_for('tabs.render', tab_id=tab.id) }}">
    <i class="fa fa-caret-left"></i>
    Back
  </a>

  <h4 class="mt-3">Versions</h4>

  <table class="table table-bordered align-middle">
    <thead>
      <th>Date added</th>
      <th>Comment</th>
      <th>File</th>
      <th>Actions</th>
    </thead>

    <tbody>
      {% for tf in tabfiles %}
        <tr>
          <td>{{ tf.date_added }}</td>
          <td>{% if tf.comment %}{{ tf.comment }}{% endif %}</td>
          <td>{{ tf.getname() }}</td>
          <td>
            <a class="btn btn-primary" href="{{ url_for('tabs.render', tab_id=tab.id, file_id=tf.id) }}" target="blank">
              <i class="fa fa-eye"></i>
              View
            </a>
            {% if tf.id != tab.fileid %}
            <a class="btn btn-outline-success" href="{{ url_for('tabs.activate_file', tab_id=tab.id, file_id=tf.id) }}">
              <i class="fa fa-hand-pointer"></i>
              Make active
            </a>
            {% else %}
              <span class="text-success ms-2">
                <i class="fa fa-check"></i>
                Active version
              </span>
            {% endif %}
            {% if current_user.is_admin and tf.id != tab.fileid %}
              <a class="btn btn-danger" href="{{ url_for('tabs.delete_file', tab_id=tab.id, file_id=tf.id) }}">
                <i class="fa fa-trash"></i>
                Delete
              </a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <h4 class="mt-3">Upload new version</h4>

  <div class="row">
    <div class="col-md-6">

      <form action="{{ url_for('tabs.upload_file', tab_id=tab.id) }}" method="post" enctype="multipart/form-data" novalidate>

        {{ form.hidden_tag() }}

        {{ f.input(form.upload_file) }}
        {{ f.input(form.comment) }}

        <button type="submit" class="btn btn-primary">
          <i class="fa fa-file-upload"></i>
          Upload
        </button>

      </form>

    </div>
  </div>

{% endblock %}